### PR TITLE
Handle for LSP textDocument/formatting request

### PR DESCRIPTION
**Pull request by PushUpek**
Fixes: #61

Handle for LSP Server textDocumnet/formatting request

### CODE REVIEW

**Comment by charliermarsh** [comment]
I need to understand how ESLint handles this before merging.

**Comment by charliermarsh** [comment]
Interesting, so after this change, Ruff is selectable as a formatter. I wonder why that _doesn't_ happen with ESLint.

Screen Shot 2023-02-13 at 3 49 18 PM

**Comment by charliermarsh** [comment]
Ah, ok -- so they have a special setting that enables it to register as a formatter:

Screen Shot 2023-02-13 at 3 56 07 PM
Screen Shot 2023-02-13 at 3 56 15 PM

We should do the same thing, I think. Although I guess that should be respected by _clients_ so it's not part of the LSP, but the client reference.

**Comment by rchl** [comment]
I suppose one could argue whether ruff really does format the document or just fixes the issues (including ordering imports). 

Since editors currently provide various functionalities to fix all issues at once (including running code actions on save), I'm not really sure if there is benefit in expose that functionality through formatting request.

**Comment by charliermarsh** [comment]
My goal was just to follow ESLint here, so I was going to disable this by default in VS Code and allow users to toggle it on. I guess that has the downside that other clients need to do the same -- but does ESLint not suffer from the same issue? Maybe they're not meant to act as a generic LSP.

**Comment by rchl** [comment]
But eslint has it disabled by default: https://github.com/microsoft/vscode-eslint/blob/705f5f5d86aab57b16c36e31f229549883d6a37f/package.json#L425-L430

It might be a bit of a legacy option because there was no "code actions on save" back when this option was introduced, I'm pretty sure.

**Comment by charliermarsh** [comment]
Right, and Ruff would too, but maybe I misunderstood what's going on? I'd thought that the ESLint LSP server always registered for the event type (https://github.com/microsoft/vscode-eslint/blob/415526ff31aeb866298514384ad401f2e4d841f5/server/src/eslintServer.ts#L1061), but that the client was responsible for enabling and disabling the behavior -- in which case, that wouldn't have any relationship to the LSP (this repo), but to the clients. I'm guessing that's an inaccurate description though?

**Comment by rchl** [comment]
I'm running this server in ST (using https://github.com/sublimelsp/LSP-eslint/) and I've just checked the server logs.

It doesn't register as a formatter when `format` is disabled.
When `format` is enabled, it decides per file whether formatting should be allowed for that file and dynamically registers formatting capability just for this file if so.

**Comment by charliermarsh** [comment]
Ahh ok, interesting. Perhaps we should roll this back then. I don't _think_ `pygls` enables us to conditionally register for capabilities.

**Comment by rchl** [comment]
I don't know `pygls` but I've looked at its code and it seems to provide the [`register_capability` method](https://github.com/openlawlibrary/pygls/blob/3fc13c4bc6eb7438e5b7e8f662d2274cf5f056c6/pygls/server.py#L429-L432). This would use the newer [dynamic capability registration](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#client_registerCapability).

The simpler option would be to just not announce formatting capabilities in the `initialize` response based on provided `initializationOptions` but that way might indeed not be supported by `pygls`.

**Pull request merged**
